server:
  port: 8530
spring:
  application:
    name: mall-order-add
  datasource:
    url: jdbc:mysql://47.100.38.50:3306/mall?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: mall
    password: jLfmazj2MzbGFR5a
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据库连接池配置
    druid:
      # 初始化 最小 最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
mybatis:
  type-aliases-package: com.mall.common.pojo
  mapper-locations: classpath:mappers/*Mapper.xml
  #  configuration:
    #  数据库中如果有类似 如  user_name 等命名，会将 _后的字母大写，这里是为了和实体类对应
    #  map-underscore-to-camel-case: true
  #pageHelper配置（官网推荐配置）
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
