server:
  port: 8300
spring:
  application:
    name: mall-admin-order-list
  datasource:
    url: jdbc:mysql://47.100.38.50:3306/mall?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: jLfmazj2MzbGFR5a
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
mybatis:
  type-aliases-package: com.mall.common.pojo
  mapper-locations: classpath:mappers/*Mapper.xml