spring:
  application:
    name: mall-zuul
server:
  port: 8766
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
zuul:
  routes:
    mall-address-list: /address/**
    mall-admin-auth: /auth/**
    mall-admin-home: /home/**
    mall-product-list: /product/**
    mall-role-list: /role/**
    mall-user-list: /user/**
    mall-admin-order-list: /order/**
    mall-admin-product-category-list: /productCategory/**
    mall-admin-product-attribute-category-list: /productAttributeCategory/**
