spring:
  application:
    name: mall-zuul
server:
  port: 8766
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
zuul:
  routes:
    mall-admin-auth: /auth/**